// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// computeGradientCPP
NumericVector computeGradientCPP(NumericVector Rparam, NumericVector Rprop, NumericMatrix Rlogu, NumericMatrix Rtik);
RcppExport SEXP ClusVis_computeGradientCPP(SEXP RparamSEXP, SEXP RpropSEXP, SEXP RloguSEXP, SEXP RtikSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Rparam(RparamSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Rprop(RpropSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Rlogu(RloguSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Rtik(RtikSEXP);
    rcpp_result_gen = Rcpp::wrap(computeGradientCPP(Rparam, Rprop, Rlogu, Rtik));
    return rcpp_result_gen;
END_RCPP
}
// computeLikelihoodCPP
NumericVector computeLikelihoodCPP(NumericVector Rparam, NumericVector Rprop, NumericMatrix Rlogu, NumericMatrix Rtik);
RcppExport SEXP ClusVis_computeLikelihoodCPP(SEXP RparamSEXP, SEXP RpropSEXP, SEXP RloguSEXP, SEXP RtikSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Rparam(RparamSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Rprop(RpropSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Rlogu(RloguSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Rtik(RtikSEXP);
    rcpp_result_gen = Rcpp::wrap(computeLikelihoodCPP(Rparam, Rprop, Rlogu, Rtik));
    return rcpp_result_gen;
END_RCPP
}
